# A workflow to create the Zubax Komar Datasheet PDF file

name: CI
on:
  push:
    paths: 'docs/datasheet/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PDF file using LaTeX

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    # Run the UAVCAN texer container with LaTeX environment
    - name: Run texer container
      uses: docker://uavcan/texer:ubuntu-16.04
      with:
        entrypoint: docs/datasheet/compile.ps1
        args: Komar.tex

    # Upload datasheet
    - name: Upload pdf as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: Zubax Komar Datasheet
        path: docs/datasheet/Komar.pdf
